### ISSUE TITLE
로컬에 적용한 내용을 바탕으로 `ci.yml` 구성

### ISSUE THREAD

**Issue by y1hongju** [dre4m1ng/spring-of-fifa#17]
autopep8, Pylint, prettier, ESLint로 구성된 CI 파이프라인을 구축합니다.

## TODO
- [x] 초기 환경 구성
- [x] autopep8, Pylint 테스팅 추가
- [ ] ~~prettier, ESLint 테스팅 추가~~

**Comment by je0nh** [comment]
fconline.py, nexon_api.py pylint 테스트 완료
<img width="696" alt="Screenshot 2024-02-20 at 2 18 41 PM" src="https://github.com/dre4m1ng/spring-of-fifa/assets/145730125/12f646d4-065a-4407-b592-398388a520c3">
