### ISSUE TITLE
Create the CD pipeline

### ISSUE THREAD

**Issue by y1hongju** [dre4m1ng/spring-of-fifa#31]
## Description

GitHub Actions를 활용하여 Amazon S3로 호스팅 되는 CRA 애플리케이션을 자동으로 관리하는 파이프라인을 구축합니다. #32 

## Process

1. 코드 checkout
2. CRA 앱 빌드
3. `aws` CLI 다운 및 설치
4. `aws` 커맨드 실행 (#32 참조)

**Comment by juhongyi** [comment]
## TODO

- [x] Fix `npm build` error (directory issue)
- [x] Fix `npm build` error (eslint warning issue)
- [x] Fix `botocore.awsrequest.AWSRequest object at 0x....` error
